parameters:
- name: azPowershellVersion
  type: string
  default: 5.5.0

steps:
- pwsh: Save-Module -Path /usr/share/az_${{ parameters.azPowershellVersion }} -Name Az -RequiredVersion ${{ parameters.azPowershellVersion }} -Force -ErrorAction Stop -Verbose
  displayName:  'Install Azure Powershell ${{ parameters.azPowershellVersion }}'