trigger:
  branches:
    include:
    - main
    - qa
    - develop
  paths:
    include:
    - infrastructure-as-code/databricks
    - infrastructure-as-code/infrastructure

variables:
- template: templates/variable.environment.yml

stages:
- template: templates/stage.plan.yml
  parameters:
    environment: ${{variables.environmentName}}
    azureServiceConnection: ${{variables.azureServiceConnection}}
    location: ${{variables.location}}
    solutionName: ${{variables.solutionName}}
    
- template: templates/stage.deploy.yml
  parameters:
    environment: ${{variables.environmentName}}
    azureServiceConnection: ${{variables.azureServiceConnection}}
    location: ${{variables.location}}
    solutionName: ${{variables.solutionName}}

- template: templates/stage.acceptance-test.yml
  parameters:
    environment: ${{variables.environmentName}}
    azureServiceConnection: ${{variables.azureServiceConnection}}
    solutionName: ${{variables.solutionName}}
